#!/usr/bin/env bash
. blissrc
LIMA_BASE_SERVER_PATH=$BLISSADM/applications/LimaCCDs

cd $LIMA_BASE_SERVER_PATH

if [ -z "$*" ]; then
    echo "Please give an instance name."
    exec python LimaCCDs.py -?
else
    exec python LimaCCDs.py $*
fi

